# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test
  pod 'handlebars-objc', :path => '../'
  pod 'YHUIKit', :git => 'git@gitlab.yonghui.cn:operation-xm-qdjg/yhuikit-ios.git', :tag => '3.0.49'
  pod 'YHFoundation', :git => 'git@gitlab.yonghui.cn:operation-xm-qdjg/yhfoundation-ios.git', :tag => '1.6.14'
  pod 'YHRouter', :git => 'http://gitlab.yonghui.cn/operation-xm-qdjg/yhrouter-ios', :tag => '3.0.3'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
